### ISSUE TITLE
艦隊の制空値や索敵スコアの表示

### ISSUE THREAD

**Issue by yamagen75** [yamagen75/KanColleRaiseSup#1]
海域攻略の支援として

制空値 = [(艦載機の対空値) × √(搭載数)] の総計（[]は端数切り捨て）
http://wikiwiki.jp/kancolle/?%B9%D2%B6%F5%C0%EF#AirSupremacy

2-5式(秋)索敵スコア[小数点第2位を四捨五入]
http://wikiwiki.jp/kancolle/?%C8%AF%C6%B0%A1%AA%DE%D5%BA%EE%C0%EF#h4f08ccf

「通称2-5式」の項目内容
http://wikiwiki.jp/kancolle/?%C6%EE%C0%BE%BD%F4%C5%E7%B3%A4%B0%E8#area5

下記サイトの計算結果と同じになれば正解とする
http://tsoft-web.com/sub/
http://www.kancolle-calc.net/

**Comment by SkyRavenHK** [comment]
初めまして。SkyRavenHK/skywalker999uです。
いつも(このChrome拡張に)お世話になっております。(笑

この機能について、索敵スコアはもうYPSで実装済みですけど、
表示について、艦隊一覧に海域の索敵スコアが満たされると一つのアイコンを緑にし、未満なら赤にしたいと思いますが、
FA3では索敵スコアに一番ふさわしいアイコンはicon-eye-openだと思います。が、FA5ではfa-binocularsがあって、それを使ったら索敵の意味がもっと分かりやすいと思います。
わたし自身の実験用verではもうFA5にアップグレード済みで、問題なく作動しています。

作者の @yamagen75 の意向を伺いたいと思います。FA3のままで、それともFA5に...?

**Comment by yamagen75** [comment]
FA5にアップグレードしても良いと思います。
